Albergo/Controllers/PrenotazioniController.cs
using Albergo.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Albergo.Controllers
{
    public class PrenotazioniController : Controller
    {
        // GET: Prenotazioni
        [Authorize]
        public ActionResult Index()
        {


            List<Prenotazione> prenotazioni = new List<Prenotazione>();
            try
            {
                Db.conn.Open();
                var command = new SqlCommand(@"SELECT Prenotazione_ID, Nome , Cognome, Data_Pren, Data_Arrivo, Data_Partenza, Numero, Tipo as TipoPensione
                                             FROM Prenotazioni as p
                                             JOIN Ospiti as o ON o.Ospite_ID = p.Ospite_ID
                                             JOIN Pensioni as pe ON pe.Pensione_ID = p.Pensione_ID
                                             JOIN Camere as c ON c.Camera_ID = p.Camera_ID", Db.conn);

                var reader = command.ExecuteReader();


                if (reader.HasRows)
                {
                    while (reader.Read())
                    {
                        var pren = new Prenotazione();
                        pren.Prenotazione_ID = (int)reader["Prenotazione_ID"];
                        pren.Ospite = new Ospite
                        {
                            Nome = reader["Nome"].ToString(),
                            Cognome = reader["Cognome"].ToString()
                        };

                        pren.Data_Pren = (DateTime)reader["Data_Pren"];
                        pren.Data_Arrivo = (DateTime)reader["Data_Arrivo"];
                        pren.Data_Partenza = (DateTime)reader["Data_Partenza"];
                        pren.Camera = new Camera { Numero = (int)reader["Numero"] };
                        pren.Pensione = new Pensione { Tipo = reader["TipoPensione"].ToString() };
                        prenotazioni.Add(pren);
                    }
                    reader.Close();
                }

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);

            }
            finally
            {
                Db.conn.Close();

            }
            return View(prenotazioni);
        }

        [Authorize]
        public ActionResult Details(int id)
        {
            var pren = new Prenotazione();
            List<PS> servizi = new List<PS>();
            decimal TotServizi = 0;
            int nottiN = 0;

            try
            {
                Db.conn.Open();
                var command = new SqlCommand(@"SELECT *, o.Nome AS NomeOspite, o.Cognome AS CognomeOspite
                FROM Prenotazioni AS p
                JOIN Pensioni AS pe ON pe.Pensione_ID = p.Pensione_ID
                JOIN Camere AS c ON c.Camera_ID = p.Camera_ID
                JOIN Camere AS cam ON cam.Camera_ID = p.Camera_ID
                JOIN Categorie AS cat ON cat.Categoria_ID = cam.Categoria_ID
                JOIN Ospiti AS o ON o.Ospite_ID = p.Ospite_ID
                WHERE Prenotazione_ID=@id", Db.conn);
                command.Parameters.AddWithValue("id", id);
                var reader = command.ExecuteReader();
                if (reader.HasRows)
                {
                    reader.Read();
                    // Calcola il numero di notti
                    DateTime dataPartenza = (DateTime)reader["Data_Partenza"];
                    DateTime dataArrivo = (DateTime)reader["Data_Arrivo"];
                    TimeSpan difference = dataPartenza - dataArrivo;
                    nottiN = difference.Days;

                    pren.Prenotazione_ID = (int)reader["Prenotazione_ID"];
                    pren.Ospite = new Ospite
                    {
                        Nome = reader["Nome"].ToString(),
                        Cognome = reader["Cognome"].ToString()
                    };

                    pren.Camera = new Camera
                    {
                        Numero = (int)reader["Numero"],
                        Categoria = new Categoria
                        {
                            Caparra = (decimal)reader["Caparra"],
                            TariffaNotte = (decimal)reader["TariffaNotte"]

                        }
                    };

                    pren.Data_Arrivo = (DateTime)reader["Data_Arrivo"];
                    pren.Data_Partenza = (DateTime)reader["Data_Partenza"];
                    pren.Pensione = new Pensione
                    {
                        Tipo = reader["Tipo"].ToString(),
                        Supplemento = (decimal)reader["Supplemento"]
                    };
                }
                reader.Close();

                var comServizi = new SqlCommand(@"SELECT *
                                         FROM PS as p
                                         JOIN Servizi as s ON s.Servizio_ID = p.Servizio_ID
                                         WHERE p.Prenotazione_ID=@id", Db.conn);
                comServizi.Parameters.AddWithValue("@id", id);
                var readerServizi = comServizi.ExecuteReader();
                if (readerServizi.HasRows)
                {
                    while (readerServizi.Read())
                    {
                        var servizio = new PS();
                        servizio.Data_Serv = (DateTime)readerServizi["Data_Serv"];
                        servizio.Quantita = (int)readerServizi["Quantita"];
                        servizio.PrezzoServ = (decimal)readerServizi["PrezzoServ"];
                        servizio.Servizio = new Servizio { Tipo = readerServizi["Tipo"].ToString() };
                        servizi.Add(servizio);
                    }
                    readerServizi.Close();
                }
                foreach (var servizio in servizi)
                {
                    TotServizi += servizio.PrezzoServ;
                }

                var totalePrenotazione = ((pren.Camera.Categoria.TariffaNotte + pren.Pensione.Supplemento) * nottiN) - pren.Camera.Categoria.Caparra + TotServizi;

                pren.Checkout = new Checkout
                {
                    Notti = nottiN,
                    TotServizi = TotServizi,
                    TotPren = totalePrenotazione
                };
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
            finally
            {
                Db.conn.Close();
            }

            return View(pren);
        }


        [Authorize]
        [HttpGet]
        public ActionResult AddServizi(int id)
        {
            var pren = new Prenotazione();
            List<PS> servizi = new List<PS>();
            decimal TotServizi = 0;
            int nottiN = 0;

            try
            {
                Db.conn.Open();
                var command = new SqlCommand(@"SELECT *, o.Nome AS NomeOspite, o.Cognome AS CognomeOspite
         FROM Prenotazioni AS p
         JOIN Pensioni AS pe ON pe.Pensione_ID = p.Pensione_ID
         JOIN Camere AS c ON c.Camera_ID = p.Camera_ID
         JOIN Camere AS cam ON cam.Camera_ID = p.Camera_ID
         JOIN Categorie AS cat ON cat.Categoria_ID = cam.Categoria_ID
         JOIN Ospiti AS o ON o.Ospite_ID = p.Ospite_ID
         WHERE Prenotazione_ID=@id", Db.conn);
                command.Parameters.AddWithValue("id", id);
                var reader = command.ExecuteReader();
                if (reader.HasRows)
                {
                    reader.Read();
                    DateTime dataPartenza = (DateTime)reader["Data_Partenza"];
                    DateTime dataArrivo = (DateTime)reader["Data_Arrivo"];
                    TimeSpan difference = dataPartenza - dataArrivo;
                    nottiN = difference.Days;

                    pren.Prenotazione_ID = (int)reader["Prenotazione_ID"];
                    pren.Ospite = new Ospite
                    {
                        Nome = reader["Nome"].ToString(),
                        Cognome = reader["Cognome"].ToString()
                    };

                    pren.Camera = new Camera
                    {
                        Numero = (int)reader["Numero"],
                        Categoria = new Categoria
                        {
                            Caparra = (decimal)reader["Caparra"],
                            TariffaNotte = (decimal)reader["TariffaNotte"]

                        }
                    };

                    pren.Data_Arrivo = (DateTime)reader["Data_Arrivo"];
                    pren.Data_Partenza = (DateTime)reader["Data_Partenza"];
                    pren.Pensione = new Pensione
                    {
                        Tipo = reader["Tipo"].ToString(),
                        Supplemento = (decimal)reader["Supplemento"]
                    };
                }
                reader.Close();

                var comServizi = new SqlCommand(@"SELECT *
                                  FROM PS as p
                                  JOIN Servizi as s ON s.Servizio_ID = p.Servizio_ID
                                  WHERE p.Prenotazione_ID=@id", Db.conn);
                comServizi.Parameters.AddWithValue("@id", id);
                var readerServizi = comServizi.ExecuteReader();
                if (readerServizi.HasRows)
                {
                    while (readerServizi.Read())
                    {
                        var servizio = new PS();
                        servizio.Data_Serv = (DateTime)readerServizi["Data_Serv"];
                        servizio.Quantita = (int)readerServizi["Quantita"];
                        servizio.PrezzoServ = (decimal)readerServizi["PrezzoServ"];
                        servizio.Servizio = new Servizio { Tipo = readerServizi["Tipo"].ToString() };
                        servizi.Add(servizio);
                    }

Albergo/Views/Prenotazioni/AddServizi.cshtml
@model Albergo.Models.Prenotazione
@{
    ViewBag.Title = "Aggiungi Servizi";
    var servizi = TempData["Servizi"] as List<Albergo.Models.Servizio>;
}


    <h2 class="mt-5 mb-4">Dettagli Soggiorno</h2>

    <table class="mb-5">
        <tr>
            <td>Prenotazione ID:</td>
            <td>@Model.Prenotazione_ID</td>
        </tr>
        <tr>
            <td>Nome:</td>
            <td>@Model.Ospite.Nome</td>
        </tr>
        <tr>
            <td>Cognome:</td>
            <td>@Model.Ospite.Cognome</td>
        </tr>
        <tr>
            <td>Numero Camera:</td>
            <td>@Model.Camera.Numero</td>
        </tr>
        <tr>
            <td>Data Arrivo:</td>
            <td>@Model.Data_Arrivo.ToShortDateString()</td>
        </tr>
        <tr>
            <td>Data Partenza:</td>
            <td>@Model.Data_Partenza.ToShortDateString()</td>
        </tr>
        @if (Model.Checkout != null)
        {
            <tr>
                <td>Notti:</td>
                <td>@Model.Checkout.Notti</td>
            </tr>
            <tr>
                <td>Totale Servizi:</td>
                <td>@Model.Checkout.TotServizi.ToString("C")</td>
            </tr>
            <tr>
                <td>Totale soggiorno camera:</td>
                <td>@Model.Checkout.TotPren.ToString("C")</td>
            </tr>
        }
        else
        {
            <tr>
                <td colspan="2">Dettagli checkout non disponibili</td>
            </tr>
        }
    </table>

    <h2 class="mb-5">Aggiungi servizi</h2>
    <form method="post" action="@Url.Action("AddServizi", "Prenotazioni")">
        <input type="hidden" id="Prenotazione_ID" name="Prenotazione_ID" value="@Model.Prenotazione_ID">
        <input type="hidden" id="selectedServizio_ID" name="selectedServizio_ID" value="" class="mb-4">
        <label class="mb-4" for="Servizio_ID">Servizio:</label>

        @if (servizi != null)
        {
            <label for="Servizio_ID"><strong>Servizio:</strong></label>
            <select id="Servizio_ID" name="Servizio_ID" class="form-control" onchange="updateSelectedServizioID(this)">
                @foreach (var servizio in servizi)
                {
                    <option value="@servizio.Servizio_ID">@servizio.Tipo</option>
                }
            </select>
        }


        <br />
        <label for="Data_Serv">Data Servizio:</label>
        <input type="date" class="mb-4" id="Data_Serv" name="Data_Serv" min="@Model.Data_Arrivo.ToString("yyyy-MM-dd")" max="@Model.Data_Partenza.ToString("yyyy-MM-dd")" onchange="filterDates()">
        <br />
        <label for="Quantita">Quantità:</label>
        <input type="number" id="Quantita" name="Quantita" min="1" class="mb-4">
        <br />
        <label for="PrezzoServ">Prezzo Servizio:</label>
        <input type="text" id="PrezzoServ" name="PrezzoServ" class="mb-4">
        <br />
        <input class="btn btn-outline-info fw-bold" type="submit" value="Aggiungi">
    </form>

    <script>
        function updateSelectedServizioID(selectElement) {
            var selectedServizioID = selectElement.value;
            document.getElementById("selectedServizio_ID").value = selectedServizioID;
        }
    </script>


    <script>
    function filterDates() {
        var dataArrivo = new Date('@Model.Data_Arrivo.ToString("yyyy-MM-dd")');
        var dataPartenza = new Date('@Model.Data_Partenza.ToString("yyyy-MM-dd")');
        var dataServInput = document.getElementById("Data_Serv");
        var dataServ = new Date(dataServInput.value);

        if (dataServ < dataArrivo || dataServ > dataPartenza) {
            dataServInput.value = '';
        }
    }
    </script>

Albergo/Views/Prenotazioni/Addpren.cshtml
@model Albergo.Models.Prenotazione

@{
    ViewBag.Title = "Nuova Prenotazione";
}

<h2 class="mt-5 mb-4">Nuova Prenotazione</h2>

@using (Html.BeginForm("AddPren", "Prenotazioni", FormMethod.Post))
{
    <div class="form-group mb-4">
        @Html.LabelFor(model => model.Data_Pren)
        @Html.EditorFor(model => model.Data_Pren, new { htmlAttributes = new { @class = "form-control", type = "datetime-local" } })
        @Html.ValidationMessageFor(model => model.Data_Pren, "", new { @class = "text-danger" })
    </div>

    <div class="form-group mb-4">
        @Html.LabelFor(model => model.Data_Arrivo)
        @Html.EditorFor(model => model.Data_Arrivo, new { htmlAttributes = new { @class = "form-control", type = "datetime-local", id = "Data_Arrivo" } })
        @Html.ValidationMessageFor(model => model.Data_Arrivo, "", new { @class = "text-danger" })
    </div>

    <div class="form-group mb-4">
        @Html.LabelFor(model => model.Data_Partenza)
        @Html.EditorFor(model => model.Data_Partenza, new { htmlAttributes = new { @class = "form-control", type = "datetime-local", id = "Data_Partenza" } })
        @Html.ValidationMessageFor(model => model.Data_Partenza, "", new { @class = "text-danger" })
    </div>

    <div id="dateError" class="text-danger mb-4" style="display: none;">
        La data di arrivo non può superare la data di partenza.
    </div>

    <div class="form-group mb-4">
        @Html.LabelFor(model => model.Pensione_ID, "Tipologia Pensione")
        @Html.DropDownListFor(model => model.Pensione_ID, new SelectList(ViewBag.Pensioni, "Pensione_ID", "Tipo"), "-- Seleziona Pensione --", new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Pensione_ID, "", new { @class = "text-danger" })
    </div>

    <div class="form-group mb-4">
        @Html.LabelFor(model => model.Ospite_ID, "ID Ospite")
        @Html.DropDownListFor(model => model.Ospite_ID, new SelectList(ViewBag.Ospiti, "Ospite_ID", "NomeCompletoCodFisc"), "-- Seleziona Ospite --", new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Ospite_ID, "", new { @class = "text-danger" })
    </div>

    <div class="form-group mb-5">
        @Html.LabelFor(model => model.Camera_ID, "N. Camera")
        @Html.DropDownListFor(model => model.Camera_ID, new SelectList(ViewBag.Camere, "Camera_ID", "Numero"), "-- Seleziona Camera --", new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Camera_ID, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <input type="submit" value="Aggiungi prenotazione" class="btn btn-primary" />
    </div>
}

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

<script>
    $(document).ready(function () {

        function validateDateRange() {
            var arrivalDate = new Date($('#Data_Arrivo').val());
            var departureDate = new Date($('#Data_Partenza').val());

            if (arrivalDate > departureDate) {

                $('#dateError').show();
                $('input[type="submit"]').prop('disabled', true);
            } else {

                $('#dateError').hide();
                $('input[type="submit"]').prop('disabled', false);
            }
        }


        $('#Data_Arrivo, #Data_Partenza').change(validateDateRange);
    });
</script>

Albergo/Views/Prenotazioni/Details.cshtml
@model Albergo.Models.Prenotazione
@{
    ViewBag.Title = "Dettagli";
}

<h2 class="mt-5 mb-4">Dettagli soggiorno ospite</h2>

<table>
    <tr>
        <td>Prenotazione ID:</td>
        <td>@Model.Prenotazione_ID</td>
    </tr>
    <tr>
        <td>Nome:</td>
        <td>@Model.Ospite.Nome</td>
    </tr>
    <tr>
        <td>Cognome:</td>
        <td>@Model.Ospite.Cognome</td>
    </tr>
    <tr>
        <td>Numero Camera:</td>
        <td>@Model.Camera.Numero</td>
    </tr>
    <tr>
        <td>Data Arrivo:</td>
        <td>@Model.Data_Arrivo.ToShortDateString()</td>
    </tr>
    <tr>
        <td>Data Partenza:</td>
        <td>@Model.Data_Partenza.ToShortDateString()</td>
    </tr>
    @if (Model.Checkout != null)
    {
        <tr>
            <td>Notti:</td>
            <td>@Model.Checkout.Notti</td>
        </tr>
        <tr>
            <td>Totale Servizi:</td>
            <td>@Model.Checkout.TotServizi.ToString("C")</td>
        </tr>
        <tr>
            <td>Totale soggiorno camera:</td>
            <td>@Model.Checkout.TotPren.ToString("C")</td>
        </tr>
    }
    else
    {
        <tr>
            <td colspan="2">Dettagli checkout non disponibili</td>
        </tr>
    }
</table>

Albergo/Views/Prenotazioni/Index.cshtml
@model List<Albergo.Models.Prenotazione>

@{
    ViewBag.Title = "Prenotazioni";
}

<h2 class="mt-5 mb-4">Prenotazioni</h2>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Prenotazione ID</th>
            <th>Data Prenotazione</th>
            <th>Data Arrivo</th>
            <th>Data Partenza</th>
            <th>Nome</th>
            <th>Cognome</th>
            <th>Numero Camera</th>
            <th>Tipo Pensione</th>
            <th>Azioni</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var prenotazione in Model)
        {
            <tr >
                <td class="pt-3 text-center">@prenotazione.Prenotazione_ID</td>
                <td class="pt-3 text-center">@prenotazione.Data_Pren.ToString("yyyy-MM-dd")</td>
                <td class="pt-3 text-center">@prenotazione.Data_Arrivo.ToString("yyyy-MM-dd")</td>
                <td class="pt-3 text-center">@prenotazione.Data_Partenza.ToString("yyyy-MM-dd")</td>
                <td class="pt-3 text-center">@prenotazione.Ospite.Nome</td>
                <td class="pt-3 text-center">@prenotazione.Ospite.Cognome</td>
                <td class="pt-3 text-center">@prenotazione.Camera.Numero</td>
                <td class="pt-3 text-center">@prenotazione.Pensione.Tipo</td>
                <td class="d-flex justify-content-evenly">
                    @Html.ActionLink("Dettagli", "Details", "Prenotazioni", new { id = prenotazione.Prenotazione_ID }, new { @class = "btn btn-outline-info me-2" })
                    @Html.ActionLink("Aggiungi servizi", "AddServizi", "Prenotazioni", new { id = prenotazione.Prenotazione_ID }, new { @class = "btn btn-outline-success" })
                </td>
            </tr>
        }
    </tbody>
</table>