Albergo/Controllers/OspitiController.cs
using Albergo.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Albergo.Controllers
{
    public class OspitiController : Controller
    {
        // GET: Ospiti
        [HttpGet]
        [Authorize]

        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(Ospite ospite)
        {
            try
            {

                Db.conn.Open();
                var cmdOspite = new SqlCommand(@"INSERT INTO Ospiti
                                           (Nome, Cognome, Citta, Provincia, Email, Telefono, Cod_Fisc)
                                           VALUES (@nome, @cognome, @citta, @prov, @email, @tel, @cod_fisc)
                                           SELECT SCOPE_IDENTITY()", Db.conn);
                cmdOspite.Parameters.AddWithValue("@nome", ospite.Nome);
                cmdOspite.Parameters.AddWithValue("@cognome", ospite.Cognome);
                cmdOspite.Parameters.AddWithValue("@citta", ospite.Citta);
                cmdOspite.Parameters.AddWithValue("@prov", ospite.Provincia);
                cmdOspite.Parameters.AddWithValue("@email", ospite.Email);
                cmdOspite.Parameters.AddWithValue("@tel", ospite.Telefono);
                cmdOspite.Parameters.AddWithValue("@cod_fisc", ospite.Cod_Fisc);
                int lastInsertedId = Convert.ToInt32(cmdOspite.ExecuteScalar());
                if (lastInsertedId > 0)
                {
                    TempData["MessageSuccess"] = "Ospite inserito con successo";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["MessageAlert"] = "Errore nell'inserimento";
                    return RedirectToAction("Index");
                }

            }
            catch (Exception ex)
            {

            }
            finally
            {
                Db.conn.Close();
            }


            return View();
        }
    }
}

Albergo/Views/Ospiti/Index.cshtml
@model Albergo.Models.Ospite

@{
    ViewBag.Title = "Nuovo Ospite";
}

@if (TempData["MessageError"] != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        @TempData["MessageError"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}
@if (TempData["MessageSuccess"] != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        @TempData["MessageSuccess"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}



<h2 class="mt-5 mb-4">Nuovo Ospite</h2>

@using (Html.BeginForm("Index", "Ospiti", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-group mb-4">
        @Html.LabelFor(model => model.Nome)
        @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
    </div>

    <div class="form-group mb-4">
        @Html.LabelFor(model => model.Cognome)
        @Html.EditorFor(model => model.Cognome, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Cognome, "", new { @class = "text-danger" })
    </div>

    <div class="form-group mb-4">
        @Html.LabelFor(model => model.Citta)
        @Html.EditorFor(model => model.Citta, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Citta, "", new { @class = "text-danger" })
    </div>

    <div class="form-group mb-4">
        @Html.LabelFor(model => model.Provincia)
        @Html.EditorFor(model => model.Provincia, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Provincia, "", new { @class = "text-danger" })
    </div>

    <div class="form-group mb-4">
        @Html.LabelFor(model => model.Email)
        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
    </div>

    <div class="form-group mb-4">
        @Html.LabelFor(model => model.Telefono)
        @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
    </div>

    <div class="form-group mb-4">
        @Html.LabelFor(model => model.Cod_Fisc)
        @Html.EditorFor(model => model.Cod_Fisc, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Cod_Fisc, "", new { @class = "text-danger" })
    </div>
    <div class="form-group my-5">
        <input type="submit" value="Inserisci Ospite" class="btn btn-outline-success" />
    </div>
}